#!/usr/bin/env bash
#
# Guardrail: reject any AI-assistant attribution trace from a commit MESSAGE.
# The human is the sole author of every commit and PR (see .claude/CLAUDE.md).
#
# Scope is deliberately NARROW — only attribution signatures, never every mention
# of "Claude"/"Anthropic" — so legitimate work (e.g. the Groq/LLM assist feature
# this app ships) and the policy docs are NOT blocked. Only the commit message
# text is scanned; staged file content is never touched.
#
# Usage: no-ai-trace.sh <file>   (e.g. the commit-msg file, $1)
#
set -euo pipefail

TARGET="${1:?usage: no-ai-trace.sh <commit-msg-file>}"
[ -f "$TARGET" ] || exit 0

# Attribution signatures emitted by AI coding tools. Case-insensitive.
PATTERN='co-authored-by:[[:space:]]*(claude|anthropic)|noreply@anthropic\.com|generated with[[:space:]]*(\[)?claude code|🤖[[:space:]]*generated|claude\.com/claude-code|claude\.ai/code|generated by claude'

if grep -qiE "$PATTERN" "$TARGET"; then
  echo "✖ Commit blocked: AI-assistant attribution trace detected in the message." >&2
  echo "  The human is the sole author. Remove traces such as:" >&2
  echo "    - 'Co-Authored-By: Claude …' / '… noreply@anthropic.com'" >&2
  echo "    - '🤖 Generated with [Claude Code]' / 'claude.com/claude-code'" >&2
  echo "  Then commit again." >&2
  exit 1
fi

exit 0
